config/routes.rb
Rails.application.routes.draw do

  resources :diagnostic_test_attempts

  get 'worksheet/get_worksheet'

  devise_for :users
  get 'short_choice_questions/index'
  root to: "home#index"

  resources :topics
  resources :short_choice_questions
  resources :chapters do 
    get :get_topics_list
  end
  resources :subjects do
    get :get_chapters_list
  end

  resources :standards do 
    get :get_subjects_list
  end

  get "/" => "home#index"

  namespace :api, :defaults => {:format => :json} do  
    resources :standards do 
      collection do
        get :get_standards
      end
    end

    resources :streams do 
      collection do
        get :get_streams
      end
    end

    resources :diagnostic_tests do 
      collection do
        get   :get_test
        get   :get_attempt_details
        post  :test_attempt
      end
    end

    resources :worksheet do 
      collection do 
        get   :get_worksheet
        post  :worksheet_attempt,:get_intro
      end
    end

    resources :homepage do 
      collection do 
        post  :get_streamwise_score, :get_streamwise_score_short
      end
    end

    resources :users do
      collection do
        post :register
      end
    end
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :standard
  has_many :chapters
  has_many :topics
  has_many :second_topics
  has_many :sub_topics
  has_many :extra_marks_questions
  has_many :short_choice_questions
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :find_subject, only: [:get_chapters_list]
  def index
    @subjects = Subject.all
  end

  def edit
  end

  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subjects_url, notice: 'Subject was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def new
    @subject = Subject.new
  end

  def show
  end

  def get_chapters_list
    @chapters = @subject.chapters
    respond_to do |format|
      format.json {render json: @chapters.pluck(:name, :id).to_json, status: 200}
      format.html
    end
  end

  private
  def subject_params
    params.require(:subject).permit(:name, :description, :full_name, :standard_id, :code)
  end

  def find_subject
    @subject = Subject.find_by_id(params[:subject_id])
    render nothing: true, status: :not_found unless @subject.present? 
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.haml
= form_for @subject do |f|
  .field
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .field
    = f.label :full_name
    = f.text_field :full_name, class: 'form-control'
  .field
    = f.label :code
    = f.text_field :code, class: 'form-control'
  .field
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .field
    = f.label :standard
    = f.select :standard_id, Standard.all.collect { |p| [ p.name, p.id ] }, include_blank: true
  = f.submit 'Save'

app/views/subjects/index.html.haml
%h3 Subjects
%table.table
  %tr
    %th Name
    %th Full name
    %th Description
    %th Class
  - @subjects.each do |s|
    %tr
      %td= s.name
      %td= s.full_name
      %td= s.description
      %td= s.standard.name

app/views/subjects/new.html.haml
.row
  .col-xs-6
    %h1 New Subject

    = render 'form'

    = link_to 'Back', subjects_path