config/routes.rb
Rails.application.routes.draw do

  resources :diagnostic_test_attempts

  get 'worksheet/get_worksheet'

  devise_for :users
  get 'short_choice_questions/index'
  root to: "home#index"

  resources :topics
  resources :short_choice_questions
  resources :chapters do 
    get :get_topics_list
  end
  resources :subjects do
    get :get_chapters_list
  end

  resources :standards do 
    get :get_subjects_list
  end

  get "/" => "home#index"

  namespace :api, :defaults => {:format => :json} do  
    resources :standards do 
      collection do
        get :get_standards
      end
    end

    resources :streams do 
      collection do
        get :get_streams
      end
    end

    resources :diagnostic_tests do 
      collection do
        get   :get_test
        get   :get_attempt_details
        post  :test_attempt
      end
    end

    resources :worksheet do 
      collection do 
        get   :get_worksheet
        post  :worksheet_attempt,:get_intro
      end
    end

    resources :homepage do 
      collection do 
        post  :get_streamwise_score, :get_streamwise_score_short
      end
    end

    resources :users do
      collection do
        post :register
      end
    end
  end

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :subject
  belongs_to :standard
  belongs_to :stream
  has_many :topics
  has_many :second_topics
  has_many :sub_topics
  validates :name, presence: true
  has_many :short_choice_questions
  has_many :extra_marks_questions
  has_many :user_entity_scores, as: :entity
  has_many :user_current_standings, as: :entity
  
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :find_chapter, only: [:get_topics_list]

  def index
    @chapters = Chapter.all
  end

  def edit
    
  end

  def show
  
  end

  def new
    @chapter = Chapter.new
  end

  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to chapters_url, notice: 'Chapter was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def get_topics_list
    @topics = @chapter.topics
    respond_to do |format|
      format.json {render json: @topics.pluck(:name, :id).to_json, status: 200}
      format.html
    end
  end

  private

  def chapter_params
    params.require(:chapter).permit(:name, :chapter_number, :subject_id, :standard_id, :code)
  end

  def find_chapter
    @chapter = Chapter.find_by_id(params[:chapter_id])
    render nothing: true, status: :not_found unless @chapter.present?
  end

end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.haml
= form_for @chapter do |f|
  .field
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .field
    = f.label :chapter_number
    = f.text_field :chapter_number, class: 'form-control'
  .field
    = f.label :code
    = f.text_field :code, class: 'form-control'
  .field
    = f.label :standard
    = f.select :standard_id, Standard.all.collect { |p| [ p.name, p.id ] }, include_blank: true
  .field
    = f.label :subject
    = f.select :subject_id, Subject.all.collect { |p| [ p.full_name, p.id ] }, include_blank: true
  
  = f.submit 'Save'

app/views/chapters/index.html.haml
%h3 Chapters
%table.table
  %tr
    %th Name
    %th Code
    %th Subject
    %th Standard
  - @chapters.each do |c|
    %tr
      %td= link_to c.name, short_choice_questions_path(:chapter_id => c.id)
      %td= c.code
      %td= c.subject.full_name
      %td= c.standard.name

app/views/chapters/new.html.haml
.row
  .col-xs-6
    %h3 New Chapter

    = render 'form'

    = link_to 'Back', chapters_path