config/routes.rb
Rails.application.routes.draw do

  resources :diagnostic_test_attempts

  get 'worksheet/get_worksheet'

  devise_for :users
  get 'short_choice_questions/index'
  root to: "home#index"

  resources :topics
  resources :short_choice_questions
  resources :chapters do 
    get :get_topics_list
  end
  resources :subjects do
    get :get_chapters_list
  end

  resources :standards do 
    get :get_subjects_list
  end

  get "/" => "home#index"

  namespace :api, :defaults => {:format => :json} do  
    resources :standards do 
      collection do
        get :get_standards
      end
    end

    resources :streams do 
      collection do
        get :get_streams
      end
    end

    resources :diagnostic_tests do 
      collection do
        get   :get_test
        get   :get_attempt_details
        post  :test_attempt
      end
    end

    resources :worksheet do 
      collection do 
        get   :get_worksheet
        post  :worksheet_attempt,:get_intro
      end
    end

    resources :homepage do 
      collection do 
        post  :get_streamwise_score, :get_streamwise_score_short
      end
    end

    resources :users do
      collection do
        post :register
      end
    end
  end

end

app/models/standard.rb
class Standard < ActiveRecord::Base
  has_many :subjects
  has_many :chapters
  has_many :topics
  has_many :second_topics
  has_many :sub_topics
  has_many :extra_marks_questions
  has_many :user_entity_scores, as: :entity
  has_many :short_choice_questions
end

app/controllers/api/standards_controller.rb
class Api::StandardsController < ApiController
  
  def get_standards
    @standards = Standard.includes(:subjects,:chapters).where(:standard_number => [6,7]).all
  end

end

app/controllers/standards_controller.rb
class StandardsController < ApplicationController
  before_action :find_standard, only: [:get_subjects_list]
  def index
    @standards = Standard.all
  end

  def edit
  end

  def new
    @standard = Standard.new 
  end

  def create
    @standard = Standard.new(standard_params)

    respond_to do |format|
      if @standard.save
        format.html { redirect_to standards_url, notice: 'Standard was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
  end

  def get_subjects_list
    @subjects = @standard.subjects
    respond_to do |format|
      format.json {render json: @subjects.pluck(:name, :id).to_json, status: 200}
      format.html
    end
  end

  private
  def standard_params
    params.require(:standard).permit(:name, :standard_number, :board, :code)
  end

  def find_standard
    @standard = Standard.find_by_id(params[:standard_id])
    render nothing: true, status: :not_found unless @standard.present? 
  end

end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/views/standards/_form.html.haml
= form_for @standard do |f|
  .field
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .field
    = f.label :standard_number
    = f.text_field :standard_number, class: 'form-control'
  .field
    = f.label :code
    = f.text_field :code, class: 'form-control'
  .field
    = f.label :board
    = f.text_field :board, class: 'form-control'
  
  = f.submit 'Save'

app/views/standards/edit.html.haml
%h1 Standards#edit
%p Find me in app/views/standards/edit.html.haml

app/views/standards/index.html.haml
%h3 Standards
%table.table
  %tr
    %th Name
    %th Standard number
    %th Board
  - @standards.each do |s|
    %tr
      %td= s.name
      %td= s.standard_number
      %td= s.board

app/views/standards/new.html.haml
.row
  .col-xs-6
    %h3 New Standard

    = render 'form'

    = link_to 'Back', standards_path