config/routes.rb
Rails.application.routes.draw do

  resources :diagnostic_test_attempts

  get 'worksheet/get_worksheet'

  devise_for :users
  get 'short_choice_questions/index'
  root to: "home#index"

  resources :topics
  resources :short_choice_questions
  resources :chapters do 
    get :get_topics_list
  end
  resources :subjects do
    get :get_chapters_list
  end

  resources :standards do 
    get :get_subjects_list
  end

  get "/" => "home#index"

  namespace :api, :defaults => {:format => :json} do  
    resources :standards do 
      collection do
        get :get_standards
      end
    end

    resources :streams do 
      collection do
        get :get_streams
      end
    end

    resources :diagnostic_tests do 
      collection do
        get   :get_test
        get   :get_attempt_details
        post  :test_attempt
      end
    end

    resources :worksheet do 
      collection do 
        get   :get_worksheet
        post  :worksheet_attempt,:get_intro
      end
    end

    resources :homepage do 
      collection do 
        post  :get_streamwise_score, :get_streamwise_score_short
      end
    end

    resources :users do
      collection do
        post :register
      end
    end
  end

end

app/models/auth_token.rb
class AuthToken < ActiveRecord::Base
  before_create :create_auth_token
  belongs_to :user

  validates :number, presence: true
  validates :user, presence: true

  CHARS = ('1'..'9').to_a + ('a'..'z').to_a  

  def create_auth_token
    self.auth_token = ""
    32.times.each{
      self.auth_token += CHARS[rand(34)+1]
    }
    self.auth_token
  end

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :subject
  belongs_to :standard
  belongs_to :stream
  has_many :topics
  has_many :second_topics
  has_many :sub_topics
  validates :name, presence: true
  has_many :short_choice_questions
  has_many :extra_marks_questions
  has_many :user_entity_scores, as: :entity
  has_many :user_current_standings, as: :entity
  
end

app/models/diagnostic_test.rb
class DiagnosticTest < ActiveRecord::Base
  belongs_to :standard
  belongs_to :subject
  belongs_to :diagnostic_test_personalization
  has_many :diagnostic_test_questions
  has_many :diagnostic_test_attempts
  has_many :users, through: :diagnostic_test_attempts
  has_many :short_choice_questions, :through => :diagnostic_test_questions,
   :source => :question, :source_type => "ShortChoiceQuestion"
  has_many :user_entity_scores, as: :test
  def self.evaluate_test question_answers

  end
end

app/models/difficulty_level.rb
class DifficultyLevel < ActiveRecord::Base
end

app/models/question_style.rb
class QuestionStyle < ActiveRecord::Base
end

app/models/second_topic.rb
class SecondTopic < ActiveRecord::Base
  belongs_to :subject
  belongs_to :standard
  belongs_to :chapter
  belongs_to :stream
  has_many :sub_topics
  has_many :short_choice_questions
  has_many :extra_marks_questions
  has_many :user_entity_scores, as: :entity
  has_many :user_current_standings, as: :entity

  has_many :children_second_topics, foreign_key: :parent_id, class_name: "SecondTopicTree" 
  has_many :children, through: :children_second_topics, source: :child

  has_many :parent_second_topics, foreign_key: :child_id, class_name: "SecondTopicTree"    
  has_many :parents, through: :parent_second_topics, source: :parent

  def stream_position
    self.id
  end

end

app/models/standard.rb
class Standard < ActiveRecord::Base
  has_many :subjects
  has_many :chapters
  has_many :topics
  has_many :second_topics
  has_many :sub_topics
  has_many :extra_marks_questions
  has_many :user_entity_scores, as: :entity
  has_many :short_choice_questions
end

app/models/stream.rb
class Stream < ActiveRecord::Base
  has_many :chapters
  has_many :topics
  has_many :second_topics
  has_many :user_current_standings
  has_many :user_entity_scores, as: :entity

  def lowest_topic_id
    self.second_topics.first.id
  end

  def lowest_topic
    self.second_topics.first
  end
end

app/models/sub_topic.rb
class SubTopic < ActiveRecord::Base
  belongs_to :subject
  belongs_to :standard
  belongs_to :chapter
  belongs_to :topic
  belongs_to :second_topic
  belongs_to :stream
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :standard
  has_many :chapters
  has_many :topics
  has_many :second_topics
  has_many :sub_topics
  has_many :extra_marks_questions
  has_many :short_choice_questions
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :subject
  belongs_to :standard
  belongs_to :chapter
  belongs_to :stream
  has_many :sub_topics
  has_many :short_choice_questions
  has_many :extra_marks_questions
  has_many :user_entity_scores, as: :entity
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :confirmable,
  #        :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: false, email: true, allow_blank: true

  has_many :user_phone_numbers
  has_many :diagnostic_test_attempts
  has_many :user_current_standings
  has_many :diagnostic_test, through: :diagnostic_test_attempts

  def find_existing_on_register user_params
    if user_params[:number]
      user = UserPhoneNumber.find_by_number(user_params[:number])
      return {:number => "already exists"} if user
    end

    if user_params[:email]
      user = User.find_by_email(user_params[:email])
      return {:email => "already taken"} if user
    end

    return false
  end

  def self.find_or_create_temp_user user_params
    if user_params[:auth_token]
      user = self.find_by_auth_token user_params[:auth_token]
      return user if user
    end

    if user_params[:number]
      user = self.find_by_phone_number(user_params[:number])
      return user if user

    end

    if user_params[:email]
      user = self.find_by_email(user_params[:email])
      return user if user
    end

    user = User.create!(:first_name => user_params[:first_name],
     :email => user_params[:email], :last_name => user_params[:last_name])
    UserPhoneNumber.create(:number => user_params[:number], :user => user)
    return user

  end

  def self.find_by_auth_token auth_token
    if auth_object = AuthToken.find_by_auth_token(auth_token) and user = auth_object.user
      return user
    else
      return false
    end
  end

  def self.find_by_phone_number number
    if cph = UserPhoneNumber.find_by_number(number) and user = cph.user
      return user
    else
      return false
    end
  end

  def generate_auth number
    AuthToken.create(:device_id => device_id, :number => number, :otp => token, :user => self)
  end

  def confirm device_id, number, token
    self.confirmed_at = Time.now
    self.save!
    self.generate_auth device_id, number, token
  end

  private

end

app/models/worksheet.rb
class Worksheet < ActiveRecord::Base
  belongs_to :standard
  belongs_to :subject
  belongs_to :stream
  belongs_to :second_topic
  belongs_to :chapter
  belongs_to :sub_topic
  belongs_to :question_style
  has_many :worksheet_scqs
  has_many :worksheet_questions
  has_many :worksheet_attempts
  has_many :difficultywise_worksheet_breakup
  has_many :users, through: :user_worksheet_attempts
  has_many :short_choice_questions, :through => :worksheet_questions,
   :source => :question, :source_type => "ShortChoiceQuestion"

  def self.evaluate_test question_answers

  end
end

app/models/worksheet_scq.rb
class WorksheetScq < ActiveRecord::Base
  belongs_to :worksheet
  belongs_to :question, :polymorphic => true
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"}
    %title Hotel
    = stylesheet_link_tag    'application', 'scaffold', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag    params[:controller]
    = javascript_include_tag params[:controller]
    = csrf_meta_tags 

    :plain
      <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
          tex2jax: {
            inlineMath: [ ['$$','$$'], ["\\(","\\)"] ],
            displayMath: [['$$$', '$$$']],
            processEscapes: true
          }
        });
      </script>
      <script type="text/javascript"
        src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
      </script>



  %body

    .container
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}
          = value

    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %a.navbar-brand{:href => "/"} Education
          %button{:type => "button", :class => "navbar-toggle", "data-toggle" => "collapse", "data-target" => "#dm-navbar"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to "Chapters", chapters_path
            %li= link_to "DTAs", diagnostic_test_attempts_path
            / - if user_signed_in?
            /   %li= link_to current_user.first_name.to_s + " (Logout)", destroy_user_session_path,  method: :delete
            / - else
            /   %li= link_to 'Login', new_user_session_path

    / #main-modal
    /   #main-modal-overlay
    /   #main-modal-content
    /     #main-modal-header
    /     #main-modal-body
    /     #main-modal-footer

    .modal.fade{ :tabindex => "-1", :role => "dialog", :id => "main-modal"}
      .modal-dialog{ :role=>"document"}
        .modal-content
          .modal-header#main-modal-header
          .modal-body#main-modal-body
          .modal-footer#main-modal-footer


    .row
      .col-xs-2
      .col-xs-8
        #page_content_column
          = yield
      .col-xs-2
        #selection_details_column